# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/blood_donation_db}

# Server Configuration
server.port=8080

# Application Properties
app.jwtSecret=${APP_JWT_SECRET:SuperSecretKeyForBloodDonationSystemNeedToBeLongEnough}
app.jwtExpirationMs=86400000
